# Generated by Django 2.2.4 on 2019-10-18 14:50

from django.db import migrations, models
import django.db.models.deletion
import mdh.utils.uuid
import mdh_data.fields.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provenance',
            fields=[
                ('metadata', mdh_data.fields.json.SmartJSONField(blank=True, help_text='Metadata associated with this object', null=True)),
                ('id', models.UUIDField(default=mdh.utils.uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True, help_text='Time at which this provenance was created')),
                ('predecessor', models.ForeignKey(blank=True, help_text='Previous provenance', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdh_provenance.Provenance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
