# Generated by Django 6.0.3 on 2026-04-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mdh_schema", "0015_alter_collection_exporters"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="collection",
            new_name="mdh_schema__slug_5880e2_idx",
            old_name="mdh_schema__slug_757907_idx",
        ),
        migrations.RenameIndex(
            model_name="property",
            new_name="mdh_schema__slug_731db0_idx",
            old_name="mdh_schema__slug_bc8f20_idx",
        ),
        migrations.RenameIndex(
            model_name="propertycollectionmembership",
            new_name="mdh_schema__propert_2001d4_idx",
            old_name="mdh_schema__propert_fdce0b_idx",
        ),
        migrations.RenameIndex(
            model_name="propertycollectionmembership",
            new_name="mdh_schema__collect_468b78_idx",
            old_name="mdh_schema__collect_62762f_idx",
        ),
    ]
