# Generated by Django 2.2.4 on 2019-10-24 11:44

from django.db import migrations, models
import django.db.models.deletion
import mdh.utils.uuid
import mdh_data.fields.json
import mdh_data.fields.ndarray


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mdh_schema', '0002_collection_flag_large_collection'),
        ('mdh_provenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=mdh.utils.uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StandardString',
            fields=[
                ('id', models.UUIDField(default=mdh.utils.uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, help_text='Is this item active')),
                ('value', models.TextField()),
                ('item', models.ForeignKey(help_text='Item this this cell represents', on_delete=django.db.models.deletion.CASCADE, to='mdh_data.Item')),
                ('prop', models.ForeignKey(help_text='Property this cell represents', on_delete=django.db.models.deletion.CASCADE, to='mdh_schema.Property')),
                ('provenance', models.ForeignKey(help_text='Provenance of this cell', on_delete=django.db.models.deletion.CASCADE, to='mdh_provenance.Provenance')),
                ('superseeded_by', models.ForeignKey(blank=True, help_text='Cell this value is superseeded by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdh_data.StandardString')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StandardJSON',
            fields=[
                ('id', models.UUIDField(default=mdh.utils.uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, help_text='Is this item active')),
                ('value', mdh_data.fields.json.SmartJSONField()),
                ('item', models.ForeignKey(help_text='Item this this cell represents', on_delete=django.db.models.deletion.CASCADE, to='mdh_data.Item')),
                ('prop', models.ForeignKey(help_text='Property this cell represents', on_delete=django.db.models.deletion.CASCADE, to='mdh_schema.Property')),
                ('provenance', models.ForeignKey(help_text='Provenance of this cell', on_delete=django.db.models.deletion.CASCADE, to='mdh_provenance.Provenance')),
                ('superseeded_by', models.ForeignKey(blank=True, help_text='Cell this value is superseeded by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdh_data.StandardJSON')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StandardInt',
            fields=[
                ('id', models.UUIDField(default=mdh.utils.uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, help_text='Is this item active')),
                ('value', models.IntegerField()),
                ('item', models.ForeignKey(help_text='Item this this cell represents', on_delete=django.db.models.deletion.CASCADE, to='mdh_data.Item')),
                ('prop', models.ForeignKey(help_text='Property this cell represents', on_delete=django.db.models.deletion.CASCADE, to='mdh_schema.Property')),
                ('provenance', models.ForeignKey(help_text='Provenance of this cell', on_delete=django.db.models.deletion.CASCADE, to='mdh_provenance.Provenance')),
                ('superseeded_by', models.ForeignKey(blank=True, help_text='Cell this value is superseeded by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdh_data.StandardInt')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StandardBool',
            fields=[
                ('id', models.UUIDField(default=mdh.utils.uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, help_text='Is this item active')),
                ('value', models.BooleanField()),
                ('item', models.ForeignKey(help_text='Item this this cell represents', on_delete=django.db.models.deletion.CASCADE, to='mdh_data.Item')),
                ('prop', models.ForeignKey(help_text='Property this cell represents', on_delete=django.db.models.deletion.CASCADE, to='mdh_schema.Property')),
                ('provenance', models.ForeignKey(help_text='Provenance of this cell', on_delete=django.db.models.deletion.CASCADE, to='mdh_provenance.Provenance')),
                ('superseeded_by', models.ForeignKey(blank=True, help_text='Cell this value is superseeded by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdh_data.StandardBool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PolynomialAsSparseArray',
            fields=[
                ('id', models.UUIDField(default=mdh.utils.uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, help_text='Is this item active')),
                ('value', mdh_data.fields.ndarray.SmartNDArrayField(dim=1, size=None, typ=models.IntegerField())),
                ('item', models.ForeignKey(help_text='Item this this cell represents', on_delete=django.db.models.deletion.CASCADE, to='mdh_data.Item')),
                ('prop', models.ForeignKey(help_text='Property this cell represents', on_delete=django.db.models.deletion.CASCADE, to='mdh_schema.Property')),
                ('provenance', models.ForeignKey(help_text='Provenance of this cell', on_delete=django.db.models.deletion.CASCADE, to='mdh_provenance.Provenance')),
                ('superseeded_by', models.ForeignKey(blank=True, help_text='Cell this value is superseeded by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdh_data.PolynomialAsSparseArray')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatrixAsList_StandardInt_3_3',
            fields=[
                ('id', models.UUIDField(default=mdh.utils.uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, help_text='Is this item active')),
                ('value', mdh_data.fields.ndarray.SmartNDArrayField(dim=1, size=None, typ=models.IntegerField())),
                ('item', models.ForeignKey(help_text='Item this this cell represents', on_delete=django.db.models.deletion.CASCADE, to='mdh_data.Item')),
                ('prop', models.ForeignKey(help_text='Property this cell represents', on_delete=django.db.models.deletion.CASCADE, to='mdh_schema.Property')),
                ('provenance', models.ForeignKey(help_text='Provenance of this cell', on_delete=django.db.models.deletion.CASCADE, to='mdh_provenance.Provenance')),
                ('superseeded_by', models.ForeignKey(blank=True, help_text='Cell this value is superseeded by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdh_data.MatrixAsList_StandardInt_3_3')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatrixAsList_StandardInt_2_2',
            fields=[
                ('id', models.UUIDField(default=mdh.utils.uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, help_text='Is this item active')),
                ('value', mdh_data.fields.ndarray.SmartNDArrayField(dim=1, size=None, typ=models.IntegerField())),
                ('item', models.ForeignKey(help_text='Item this this cell represents', on_delete=django.db.models.deletion.CASCADE, to='mdh_data.Item')),
                ('prop', models.ForeignKey(help_text='Property this cell represents', on_delete=django.db.models.deletion.CASCADE, to='mdh_schema.Property')),
                ('provenance', models.ForeignKey(help_text='Provenance of this cell', on_delete=django.db.models.deletion.CASCADE, to='mdh_provenance.Provenance')),
                ('superseeded_by', models.ForeignKey(blank=True, help_text='Cell this value is superseeded by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdh_data.MatrixAsList_StandardInt_2_2')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListAsArray_StandardJSON',
            fields=[
                ('id', models.UUIDField(default=mdh.utils.uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, help_text='Is this item active')),
                ('value', mdh_data.fields.ndarray.SmartNDArrayField(blank=True, dim=1, null=True, size=None, typ=mdh_data.fields.json.SmartJSONField())),
                ('item', models.ForeignKey(help_text='Item this this cell represents', on_delete=django.db.models.deletion.CASCADE, to='mdh_data.Item')),
                ('prop', models.ForeignKey(help_text='Property this cell represents', on_delete=django.db.models.deletion.CASCADE, to='mdh_schema.Property')),
                ('provenance', models.ForeignKey(help_text='Provenance of this cell', on_delete=django.db.models.deletion.CASCADE, to='mdh_provenance.Provenance')),
                ('superseeded_by', models.ForeignKey(blank=True, help_text='Cell this value is superseeded by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdh_data.ListAsArray_StandardJSON')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListAsArray_StandardInt',
            fields=[
                ('id', models.UUIDField(default=mdh.utils.uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, help_text='Is this item active')),
                ('value', mdh_data.fields.ndarray.SmartNDArrayField(blank=True, dim=1, null=True, size=None, typ=models.IntegerField())),
                ('item', models.ForeignKey(help_text='Item this this cell represents', on_delete=django.db.models.deletion.CASCADE, to='mdh_data.Item')),
                ('prop', models.ForeignKey(help_text='Property this cell represents', on_delete=django.db.models.deletion.CASCADE, to='mdh_schema.Property')),
                ('provenance', models.ForeignKey(help_text='Provenance of this cell', on_delete=django.db.models.deletion.CASCADE, to='mdh_provenance.Provenance')),
                ('superseeded_by', models.ForeignKey(blank=True, help_text='Cell this value is superseeded by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdh_data.ListAsArray_StandardInt')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemCollectionAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdh_schema.Collection')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdh_data.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='collections',
            field=models.ManyToManyField(blank=True, help_text='Collection(s) each item occurs in', through='mdh_data.ItemCollectionAssociation', to='mdh_schema.Collection'),
        ),
        migrations.CreateModel(
            name='GraphAsSparse6',
            fields=[
                ('id', models.UUIDField(default=mdh.utils.uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, help_text='Is this item active')),
                ('value', models.TextField()),
                ('item', models.ForeignKey(help_text='Item this this cell represents', on_delete=django.db.models.deletion.CASCADE, to='mdh_data.Item')),
                ('prop', models.ForeignKey(help_text='Property this cell represents', on_delete=django.db.models.deletion.CASCADE, to='mdh_schema.Property')),
                ('provenance', models.ForeignKey(help_text='Provenance of this cell', on_delete=django.db.models.deletion.CASCADE, to='mdh_provenance.Provenance')),
                ('superseeded_by', models.ForeignKey(blank=True, help_text='Cell this value is superseeded by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdh_data.GraphAsSparse6')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='standardstring',
            index=models.Index(fields=['item'], name='mdh_data_st_item_id_4d9502_idx'),
        ),
        migrations.AddIndex(
            model_name='standardstring',
            index=models.Index(fields=['prop'], name='mdh_data_st_prop_id_bb94ce_idx'),
        ),
        migrations.AddIndex(
            model_name='standardstring',
            index=models.Index(fields=['active'], name='mdh_data_st_active_32b893_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='standardstring',
            unique_together={('item', 'prop', 'superseeded_by')},
        ),
        migrations.AddIndex(
            model_name='standardjson',
            index=models.Index(fields=['item'], name='mdh_data_st_item_id_2c1d86_idx'),
        ),
        migrations.AddIndex(
            model_name='standardjson',
            index=models.Index(fields=['prop'], name='mdh_data_st_prop_id_5479dd_idx'),
        ),
        migrations.AddIndex(
            model_name='standardjson',
            index=models.Index(fields=['active'], name='mdh_data_st_active_73a179_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='standardjson',
            unique_together={('item', 'prop', 'superseeded_by')},
        ),
        migrations.AddIndex(
            model_name='standardint',
            index=models.Index(fields=['item'], name='mdh_data_st_item_id_253a32_idx'),
        ),
        migrations.AddIndex(
            model_name='standardint',
            index=models.Index(fields=['prop'], name='mdh_data_st_prop_id_43d25f_idx'),
        ),
        migrations.AddIndex(
            model_name='standardint',
            index=models.Index(fields=['active'], name='mdh_data_st_active_c1890f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='standardint',
            unique_together={('item', 'prop', 'superseeded_by')},
        ),
        migrations.AddIndex(
            model_name='standardbool',
            index=models.Index(fields=['item'], name='mdh_data_st_item_id_bb66ec_idx'),
        ),
        migrations.AddIndex(
            model_name='standardbool',
            index=models.Index(fields=['prop'], name='mdh_data_st_prop_id_f993f0_idx'),
        ),
        migrations.AddIndex(
            model_name='standardbool',
            index=models.Index(fields=['active'], name='mdh_data_st_active_1007b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='standardbool',
            unique_together={('item', 'prop', 'superseeded_by')},
        ),
        migrations.AddIndex(
            model_name='polynomialassparsearray',
            index=models.Index(fields=['item'], name='mdh_data_po_item_id_09c341_idx'),
        ),
        migrations.AddIndex(
            model_name='polynomialassparsearray',
            index=models.Index(fields=['prop'], name='mdh_data_po_prop_id_1f3632_idx'),
        ),
        migrations.AddIndex(
            model_name='polynomialassparsearray',
            index=models.Index(fields=['active'], name='mdh_data_po_active_b4fcc8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='polynomialassparsearray',
            unique_together={('item', 'prop', 'superseeded_by')},
        ),
        migrations.AddIndex(
            model_name='matrixaslist_standardint_3_3',
            index=models.Index(fields=['item'], name='mdh_data_ma_item_id_f852f3_idx'),
        ),
        migrations.AddIndex(
            model_name='matrixaslist_standardint_3_3',
            index=models.Index(fields=['prop'], name='mdh_data_ma_prop_id_02bd51_idx'),
        ),
        migrations.AddIndex(
            model_name='matrixaslist_standardint_3_3',
            index=models.Index(fields=['active'], name='mdh_data_ma_active_80c180_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='matrixaslist_standardint_3_3',
            unique_together={('item', 'prop', 'superseeded_by')},
        ),
        migrations.AddIndex(
            model_name='matrixaslist_standardint_2_2',
            index=models.Index(fields=['item'], name='mdh_data_ma_item_id_0038fe_idx'),
        ),
        migrations.AddIndex(
            model_name='matrixaslist_standardint_2_2',
            index=models.Index(fields=['prop'], name='mdh_data_ma_prop_id_649f1a_idx'),
        ),
        migrations.AddIndex(
            model_name='matrixaslist_standardint_2_2',
            index=models.Index(fields=['active'], name='mdh_data_ma_active_ab47bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='matrixaslist_standardint_2_2',
            unique_together={('item', 'prop', 'superseeded_by')},
        ),
        migrations.AddIndex(
            model_name='listasarray_standardjson',
            index=models.Index(fields=['item'], name='mdh_data_li_item_id_2767c3_idx'),
        ),
        migrations.AddIndex(
            model_name='listasarray_standardjson',
            index=models.Index(fields=['prop'], name='mdh_data_li_prop_id_8f5db3_idx'),
        ),
        migrations.AddIndex(
            model_name='listasarray_standardjson',
            index=models.Index(fields=['active'], name='mdh_data_li_active_3f0b10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listasarray_standardjson',
            unique_together={('item', 'prop', 'superseeded_by')},
        ),
        migrations.AddIndex(
            model_name='listasarray_standardint',
            index=models.Index(fields=['item'], name='mdh_data_li_item_id_ab9e25_idx'),
        ),
        migrations.AddIndex(
            model_name='listasarray_standardint',
            index=models.Index(fields=['prop'], name='mdh_data_li_prop_id_e5fa8c_idx'),
        ),
        migrations.AddIndex(
            model_name='listasarray_standardint',
            index=models.Index(fields=['active'], name='mdh_data_li_active_c8c30d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listasarray_standardint',
            unique_together={('item', 'prop', 'superseeded_by')},
        ),
        migrations.AddIndex(
            model_name='itemcollectionassociation',
            index=models.Index(fields=['item'], name='mdh_data_it_item_id_06636f_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcollectionassociation',
            index=models.Index(fields=['collection'], name='mdh_data_it_collect_d5b54b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcollectionassociation',
            unique_together={('item', 'collection')},
        ),
        migrations.AddIndex(
            model_name='graphassparse6',
            index=models.Index(fields=['item'], name='mdh_data_gr_item_id_da3b10_idx'),
        ),
        migrations.AddIndex(
            model_name='graphassparse6',
            index=models.Index(fields=['prop'], name='mdh_data_gr_prop_id_231816_idx'),
        ),
        migrations.AddIndex(
            model_name='graphassparse6',
            index=models.Index(fields=['active'], name='mdh_data_gr_active_d649bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='graphassparse6',
            unique_together={('item', 'prop', 'superseeded_by')},
        ),
    ]
