# Generated by Django 2.2.4 on 2019-10-29 13:08

from django.db import migrations, models
import django.db.models.deletion
import mdh.utils.uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mdh_provenance', '0001_initial'),
        ('mdh_schema', '0006_prefilter_count'),
        ('mdh_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoveringRelationAsDigraph6',
            fields=[
                ('id', models.UUIDField(default=mdh.utils.uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, help_text='Is this item active')),
                ('value', models.TextField()),
                ('item', models.ForeignKey(help_text='Item this this cell represents', on_delete=django.db.models.deletion.CASCADE, to='mdh_data.Item')),
                ('prop', models.ForeignKey(help_text='Property this cell represents', on_delete=django.db.models.deletion.CASCADE, to='mdh_schema.Property')),
                ('provenance', models.ForeignKey(help_text='Provenance of this cell', on_delete=django.db.models.deletion.CASCADE, to='mdh_provenance.Provenance')),
                ('superseeded_by', models.ForeignKey(blank=True, help_text='Cell this value is superseeded by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdh_data.CoveringRelationAsDigraph6')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='coveringrelationasdigraph6',
            index=models.Index(fields=['item'], name='mdh_data_co_item_id_19507f_idx'),
        ),
        migrations.AddIndex(
            model_name='coveringrelationasdigraph6',
            index=models.Index(fields=['prop'], name='mdh_data_co_prop_id_317cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='coveringrelationasdigraph6',
            index=models.Index(fields=['active'], name='mdh_data_co_active_18ddec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coveringrelationasdigraph6',
            unique_together={('item', 'prop', 'superseeded_by')},
        ),
    ]
