# Generated by Django 3.2.15 on 2022-10-11 08:57

from django.db import migrations, models
import django.db.models.deletion
import mdh.utils.uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mdh_provenance', '0002_alter_provenance_metadata'),
        ('mdh_schema', '0015_alter_collection_exporters'),
        ('mdh_data', '0005_auto_20220708_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagmaGraphCode',
            fields=[
                ('id', models.UUIDField(default=mdh.utils.uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, help_text='Is this item active')),
                ('value', models.TextField()),
                ('item', models.ForeignKey(help_text='Item this this cell represents', on_delete=django.db.models.deletion.CASCADE, to='mdh_data.item')),
                ('prop', models.ForeignKey(help_text='Property this cell represents', on_delete=django.db.models.deletion.CASCADE, to='mdh_schema.property')),
                ('provenance', models.ForeignKey(help_text='Provenance of this cell', on_delete=django.db.models.deletion.CASCADE, to='mdh_provenance.provenance')),
                ('superseeded_by', models.ForeignKey(blank=True, help_text='Cell this value is superseeded by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdh_data.magmagraphcode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='magmagraphcode',
            index=models.Index(fields=['item'], name='mdh_data_ma_item_id_73710f_idx'),
        ),
        migrations.AddIndex(
            model_name='magmagraphcode',
            index=models.Index(fields=['prop'], name='mdh_data_ma_prop_id_886604_idx'),
        ),
        migrations.AddIndex(
            model_name='magmagraphcode',
            index=models.Index(fields=['active'], name='mdh_data_ma_active_f097f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='magmagraphcode',
            unique_together={('item', 'prop', 'superseeded_by')},
        ),
    ]
