# Generated by Django 6.0.3 on 2026-04-19 18:26

import django.db.models.deletion
import mdh.utils.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mdh_data",
            "0007_rename_mdh_data_co_item_id_19507f_idx_mdh_data_co_item_id_edba43_idx_and_more",
        ),
        ("mdh_provenance", "0002_alter_provenance_metadata"),
        (
            "mdh_schema",
            "0016_rename_mdh_schema__slug_757907_idx_mdh_schema__slug_5880e2_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.TextField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ExternalLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=mdh.utils.uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, help_text="Is this item active"),
                ),
                ("link_data", models.JSONField()),
                (
                    "item",
                    models.ForeignKey(
                        help_text="Item this this cell represents",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mdh_data.item",
                    ),
                ),
                (
                    "prop",
                    models.ForeignKey(
                        help_text="Property this cell represents",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mdh_schema.property",
                    ),
                ),
                (
                    "provenance",
                    models.ForeignKey(
                        help_text="Provenance of this cell",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mdh_provenance.provenance",
                    ),
                ),
                (
                    "superseeded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cell this value is superseeded by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mdh_data.externallink",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mdh_data.externalsource",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["item"], name="mdh_data_ex_item_id_9d5db2_idx"
                    ),
                    models.Index(
                        fields=["prop"], name="mdh_data_ex_prop_id_832655_idx"
                    ),
                    models.Index(
                        fields=["active"], name="mdh_data_ex_active_054c79_idx"
                    ),
                ],
                "unique_together": {("item", "prop", "superseeded_by")},
            },
        ),
    ]
