name: Docker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the Docker Image

    steps:
    - uses: actions/checkout@v6
    - run: docker build -t imfm-si/mdh .
